local srcery = require((...):match '(.+)%.[^.]+' .. '.srcery')

-- * List of palette colors:
--   https://github.com/Iron-E/nvim-highlite/blob/v4.15.1/doc/advanced-usage.md#list-of-palette-colors
-- * What color will be used if missing:
--   https://github.com/Iron-E/nvim-highlite/blob/v4.15.1/lua/highlite/color/palette/init.lua#L100-L196
return {
   -- annotation = , --> attribute
   -- attribute = ,  --> preproc
   bg = srcery.black,
   bg_contrast_high = srcery.xgray2,
   bg_contrast_low = srcery.hard_black,
   boolean = srcery.bright_magenta,
   -- buffer_active = ,    --> text_contrast_bg_high
   -- buffer_alternate = , --> text_contrast_bg_low
   -- buffer_current = ,   --> select
   character = srcery.bright_magenta,
   -- character_special = , --> special
   -- class = , --> structure
   -- comment = , --> text_contrast_bg_low
   -- comment_documentation = , --> comment
   comment_special = srcery.orange, -- NOTE: missing in upstream
   conditional = srcery.red,
   constant = srcery.bright_magenta,
   -- constant_builtin = , --> special
   -- constructor = , --> type
   -- decorator = , --> attribute
   define = srcery.cyan,
   diff_add = srcery.green,
   diff_change = srcery.cyan,
   diff_delete = srcery.red,
   -- enum = , --> structure
   error = srcery.bright_red,
   -- event = , --> loop
   -- field = , --> property
   -- field_enum = , --> constant
   -- float = , --> number
   fold = srcery.bright_black,
   func = srcery.yellow,
   -- func_builtin = , --> special
   hint = srcery.bright_cyan,
   identifier = srcery.cyan,
   -- include = , --> preproc
   info = srcery.bright_green,
   -- interface = , --> type
   -- interface_builtin = ,
   -- keyword = , --> statement
   -- keyword_coroutine = , --> keyword
   -- keyword_function = , --> type_builtin
   -- keyword_operator = , --> operator
   -- keyword_return = , --> keyword
   label = srcery.red,
   -- loop =, --> conditional
   macro = srcery.orange,
   -- message = , --> info
   -- method = , --> func
   -- namespace = , --> uri
   number = srcery.bright_magenta,
   ok = srcery.bright_green,
   operator = srcery.bright_white,
   -- parameter = , --> identifier
   preproc = srcery.cyan,
   -- preproc_conditional = , --> preproc
   -- property = , --> identifier
   -- punctuation = , --> text_contrast_bg_high
   -- punctuation_bracket = , --> punctuation
   -- punctuation_delimiter = , --> punctuation
   punctuation_special = srcery.magenta, --> string_special
   search = srcery.xgray5,
   select = srcery.xgray2, --> bg_contrast_low
   special = srcery.orange,
   statement = srcery.red,
   storage = srcery.orange,
   string = srcery.bright_green,
   -- string_escape = , --> character
   -- string_regex = , --> string
   string_special = srcery.magenta, --> identifier
   structure = srcery.cyan,
   -- syntax_error = , --> error
   -- tag = , --> structure
   -- tag_attribute = , --> field
   -- tag_delimiter = , --> punctuation_bracket
   text = srcery.bright_white,
   text_contrast_bg_high = srcery.bright_black,
   text_contrast_bg_low = srcery.white,
   -- text_environment_name = , --> label
   -- text_environment = , --> text_contrast_bg_low
   -- text_literal = , --> statement
   -- text_math = , --> number
   -- text_reference = , --> uri
   -- throw = , --> error
   todo = srcery.bright_white,
   type = srcery.bright_blue,
   -- type_builtin = , --> type
   -- type_parameter = , --> type
   uri = srcery.blue, --> text
   -- variable = , --> identifier
   -- variable_builtin = , --> keyword
   warning = srcery.bright_yellow,
}
